
#All values are calculated in minecraft ticks,
#20 ticks = 1 second.
#The timer always displays complete remaining seconds,
#so 620 ticks = 30 seconds displayed by the timer.
[Configs]
	#Default amount of ticks recovered per tick recover. [default:1]
	#Range: > 1
	"Default amount recovered" = 1
	#Set to true to stop the timer for all players once one of them met the conditions
	Co-op = false
	#Set to true to use the same shared timer for all dimensions
	"Global timer" = false
	#Default duration when the player comes for the first time in this dimension. [default:12000 = 10 minutes]
	#Range: > 0
	"Default duration" = 12000
	#Dimensions where there is NO timer
	BlackList = ["minecraft:overworld"]
	#When time is up, the player die if set to false or receive bad potion effects if set to true
	"Potion Effects" = true
	#Default max duration that can be accumulated for a dimension. [default:72000 = 1 hour]
	#Range: > 0
	"Default max duration" = 36000
	#'BlackList' is used as a blacklist if true.
	#'BlackList' is used as a whitelist otherwise.
	"Use blackList" = true
	#Default tick amount to spend in an other dimension to recover ticks in this dimension. [default:4]
	#Range: > 1
	"Default ticks per duration" = 4
	#Tick when the timer comes in the front of the screen [default:220]
	#Range: > 0
	Emergency = 220
	#Default timer for each dimension.
	#Format for one dimension : "dimension_id;default_duration;ticks_per_duration;max_duration;amount_recovered".
	#Example : "minecraft:the_nether;12000;4;72000;3"
	"Default timers" = ["minecraft:the_end;36000;4;36000;1"]
	#Play a warning sound at these ticks. [default: [1220, 620] ]
	Warnings = [1220, 620]
	#Tick when the timer becomes red. [default:620]
	#Range: > 0
	Dangerous = 620
	#The player respawns at default spawnpoint if their spawnpoint is set to a dimension with little time left.
	#Set to false to disable this.
	"Safe Respawn" = true

[Boss]
	#NBT of the boss.
	#Every entity matching this NBT is considered as boss.
	#Once the player has killed the boss, his timers are disabled.
	#Leaving this blank will disable boss functionality.
	Boss = ""
	#Message sent when the player killed the boss.
	"Boss message" = "ยง6You are now free to travel across dimensions without any limit."

[Effects]
	#Sets effects for dangerous phase. format : effectId;duration;amplifier;show_icon
	"dangerous effects" = ["minecraft:slowness;120;1;true"]
	#Cooldown before applying effects. [80 ticks by default]
	#Range: > 1
	"effects cooldown" = 80
	#Sets effects for when the time is up. format : effectId;duration;amplifier;show_icon
	"time is up effects" = ["minecraft:slowness;120;3;true", "minecraft:mining_fatigue;120;1;true", "minecraft:poison;120;2;true", "minecraft:hunger;120;1;true"]
	#Sets mobs that can be spawned by doom effect.
	#If a dimension or biome is not set, default spawnset for biome will be used.
	#format :  dimension_or_biome_name;entry1;entry2; ...
	#entry format : entity_name,weight,minCount,maxCount
	#weight - higher weight mean higher chance to spawn
	#minCount - minimum group size
	#maxCount - maximum group size
	"Doom spawners" = []
	#Exile Effect amplifier
	#Range: 0 ~ 255
	"Exile amplifier" = 0
	#Chances to get Exile Effect by killing a mob.
	#Range: 0.0 ~ 1.0
	"Exile chances" = 0.0
	#Sets effects for emergency phase. format : effectId;duration;amplifier;show_icon
	"emergency effects" = ["minecraft:slowness;120;1;true", "minecraft:mining_fatigue;120;0;true", "minecraft:poison;120;0;true", "minecraft:hunger;120;0;true"]
	#Sets the spawn chance when doom performs its effect.
	#Assuming nothing else is preventing spawning.
	#Range: 0.0 ~ 1.0
	"Doom spawn chance" = 0.6

